[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
authors = ["{{author}} <{{email}}>"]
license = "MIT OR Apache-2.0"
edition = "2024"
rust-version = "1.88.0"

[workspace.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
