[package]
name = "my_crate"
publish = false
version = "0.1.0"
description = "{{desc}}"
include = ["src", "LICENSE*"]
keywords = []
categories = []
readme = "README.md"
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
